"""Initial migration

Revision ID: 77c80644546a
Revises: 
Create Date: 2025-11-15 17:36:41.213520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77c80644546a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_keepalive', sa.DateTime(timezone=True), nullable=True),
    sa.Column('basic_auth_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('telegram_bot_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telegram_channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_name'), 'space', ['name'], unique=True)
    op.create_table('spaceevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('OPEN', 'CLOSED', 'UNKNOWN', name='spaceeventstate'), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spaceevent_timestamp'), 'spaceevent', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spaceevent_timestamp'), table_name='spaceevent')
    op.drop_table('spaceevent')
    op.drop_index(op.f('ix_space_name'), table_name='space')
    op.drop_table('space')
    # ### end Alembic commands ###
